server:
  port: 10000

spring:
  datasource:
    username: rjbf4
    password: 123456
    url: jdbc:mysql://175.178.189.140:3306/myapp?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.org.entity

configuration:
  map-underscore-to-camel-case:true