server:
  port: 9001
spring:
  application:
    name: gateway-9001
  redis:
    port: 6379
    host: 175.178.189.140
    password: saiGou_70852096
  cloud:
    gateway:
      enabled: true # 只要加了依赖，默认开启
      discovery:
        locator:
          enabled: true     # 开启动态路由、通用应用名称，找到服务的功能
          lower-case-service-id: true # 开启服务名称小写

# Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/
    registry-fetch-interval-seconds: 3    # 网关拉去服务列表的时间缩短
  intstance:
    instance-id: gateway-9001
    prefer-ip-address: true # 显示服务的ip地址





