server:
  port: 8089
spring:
  application:
    name: student-find-8089
  redis: # redis
    port: 6379
    host: 175.178.189.140
    password: saiGou_70852096
  datasource: # Mysql
    #    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://175.178.189.140:3306/myapp?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: rjbf4
    password: 123456
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 0.1  # ??????????????0.1??10%?1??????
        rate: 10  # ?????????????????????trace???????0????2147483647
# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # ????
    map-underscore-to-camel-case: true
    # ??????
    cache-enabled: false
    # ??sql
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # ????
  global-config:
    # ????????????
    db-column-underline: true
    # id????(???id??)
    id-type: 0

  type-aliases-package: com.org.model


# Eureka???????????
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/
  intstance:
    instance-id: student-find-8089
    prefer-ip-address: true # ?????ip??