# ???? WEB ????
server:
    port: 7001
# ????
spring:
    application:
        name: eureka-7001
# Eureka??
eureka:
    instance:
        hostname: eureka7001.com # Eureka????????
    client:
        register-with-eureka: false # ?????eurekaz????????
        fetch-registry: false #???false???????????
        service-url:
            defaultZone: http://eureka7002.com:7002/eureka/

